RMOL::HistoricalBooking Struct Reference
RMOL::HistoricalBooking Struct Reference
Structure keeping track, for a given class, of the number of historical bookings and of the censorship flag.
#include <rmol/bom/HistoricalBooking.hpp>
Public Member Functions
const stdair::NbOfBookings_T & getNbOfBookings () const
const stdair::NbOfBookings_T & getUnconstrainedDemand () const
const stdair::Flag_T & getFlag () const
void setUnconstrainedDemand (const stdair::NbOfBookings_T &iDemand)
void setParameters (const stdair::NbOfBookings_T, const stdair::Flag_T)
void toStream (std::ostream &ioOut) const
const std::string describe () const
void display () const
HistoricalBooking (const stdair::NbOfBookings_T, const stdair::Flag_T)
HistoricalBooking ()
HistoricalBooking (const HistoricalBooking &)
virtual ~HistoricalBooking ()
Detailed Description
Structure keeping track, for a given class, of the number of historical bookings and of the censorship flag.
Definition at line 17 of file HistoricalBooking.hpp.
Constructor & Destructor Documentation
RMOL::HistoricalBooking::HistoricalBooking (const stdair::NbOfBookings_T iNbOfBookings, const stdair::Flag_T iFlag)
Main constructor.
Definition at line 21 of file HistoricalBooking.cpp.
RMOL::HistoricalBooking::HistoricalBooking ()
Default constructor.
Definition at line 15 of file HistoricalBooking.cpp.
RMOL::HistoricalBooking::HistoricalBooking (const HistoricalBooking & iHistoricalBooking)
Copy constructor.
Definition at line 29 of file HistoricalBooking.cpp.
RMOL::HistoricalBooking::~HistoricalBooking () virtual
Destructor.
Definition at line 36 of file HistoricalBooking.cpp.
Member Function Documentation
const stdair::NbOfBookings_T& RMOL::HistoricalBooking::getNbOfBookings () const inline
Getter for the booking.
Definition at line 22 of file HistoricalBooking.hpp.
Referenced by RMOL::HistoricalBookingHolder::calculateExpectedDemand(), RMOL::HistoricalBookingHolder::getHistoricalBooking(), RMOL::HistoricalBookingHolder::getNbOfUncensoredBookings(), RMOL::HistoricalBookingHolder::getUncensoredStandardDeviation(), toStream(), and RMOL::HistoricalBookingHolder::toStream().
const stdair::NbOfBookings_T& RMOL::HistoricalBooking::getUnconstrainedDemand () const inline
Getter for the unconstrained bookings.
Definition at line 26 of file HistoricalBooking.hpp.
Referenced by RMOL::HistoricalBookingHolder::getDemandMean(), RMOL::HistoricalBookingHolder::getStandardDeviation(), RMOL::HistoricalBookingHolder::getUnconstrainedDemand(), toStream(), and RMOL::HistoricalBookingHolder::toStream().
const stdair::Flag_T& RMOL::HistoricalBooking::getFlag () const inline
Getter for the flag of censorship: "false" means that the bookings are not censored.
Definition at line 31 of file HistoricalBooking.hpp.
Referenced by RMOL::HistoricalBookingHolder::getCensorshipFlag(), RMOL::HistoricalBookingHolder::getListOfToBeUnconstrainedFlags(), RMOL::HistoricalBookingHolder::getNbOfUncensoredBookings(), toStream(), and RMOL::HistoricalBookingHolder::toStream().
void RMOL::HistoricalBooking::setUnconstrainedDemand (const stdair::NbOfBookings_T & iDemand) inline
Setter for the unconstraining demand.
Definition at line 38 of file HistoricalBooking.hpp.
void RMOL::HistoricalBooking::setParameters (const stdair::NbOfBookings_T iNbOfBookings, const stdair::Flag_T iFlag)
Setter for all parameters.
Definition at line 41 of file HistoricalBooking.cpp.
void RMOL::HistoricalBooking::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream
Returns
ostream& the output stream.
Definition at line 57 of file HistoricalBooking.cpp.
References getFlag(), getNbOfBookings(), and getUnconstrainedDemand().
Referenced by display().
const std::string RMOL::HistoricalBooking::describe () const
Give a description of the structure (for display purposes).
Definition at line 48 of file HistoricalBooking.cpp.
void RMOL::HistoricalBooking::display () const
Display on standard output.
Definition at line 66 of file HistoricalBooking.cpp.
References toStream().
The documentation for this struct was generated from the following files:
rmol/bom/HistoricalBooking.hpp
rmol/bom/HistoricalBooking.cpp