RMOL::Emsr Class Reference
RMOL::Emsr Class Reference
#include <rmol/bom/Emsr.hpp>
Static Public Member Functions
static void heuristicOptimisationByEmsr (stdair::LegCabin &)
static void heuristicOptimisationByEmsrA (stdair::LegCabin &)
static void heuristicOptimisationByEmsrB (stdair::LegCabin &)
Detailed Description
Class Implementing the EMSR algorithm for Bid-Price Vector computing.
Definition at line 18 of file Emsr.hpp.
Member Function Documentation
void RMOL::Emsr::heuristicOptimisationByEmsr (stdair::LegCabin & ioLegCabin) static
Compute the Bid-Price Vector using the EMSR algorithm. Then compute the protection levels and booking limits by using the BPV.
For each class/bucket j with yield pj and demand Dj, compute pj*Pr(Dj>=x) with x the capacity index. This value is called the EMSR (Expected Marginal Seat Revenue) of the class/bucket j with the remaining capacity of x. Thus, we have for each class/bucket a list of EMSR values. We merge all these lists and sort the values from high to low in order to obtain the BPV.
Definition at line 108 of file Emsr.cpp.
References RMOL::EmsrUtils::computeEmsrValue().
Referenced by RMOL::Optimiser::heuristicOptimisationByEmsr().
void RMOL::Emsr::heuristicOptimisationByEmsrA (stdair::LegCabin & ioLegCabin) static
Calculate the optimal protections for the set of buckets/classes given in input, and update those buckets accordingly.
Definition at line 21 of file Emsr.cpp.
References RMOL::EmsrUtils::computeProtectionLevel().
Referenced by RMOL::Optimiser::heuristicOptimisationByEmsrA().
void RMOL::Emsr::heuristicOptimisationByEmsrB (stdair::LegCabin & ioLegCabin) static
Complute the protection levels and booking limites by using the EMSR-b algorithm.
Definition at line 64 of file Emsr.cpp.
References RMOL::EmsrUtils::computeAggregatedVirtualClass(), and RMOL::EmsrUtils::computeProtectionLevel().
Referenced by RMOL::Optimiser::heuristicOptimisationByEmsrB().
The documentation for this class was generated from the following files:
rmol/bom/Emsr.hpp
rmol/bom/Emsr.cpp