RMOL::EMDetruncator Class Reference
RMOL::EMDetruncator Class Reference
#include <rmol/bom/EMDetruncator.hpp>
Static Public Member Functions
static void unconstrain (HistoricalBookingHolder &)
Detailed Description
Utility for the Expectation-Maximisation algorithm.
Definition at line 12 of file EMDetruncator.hpp.
Member Function Documentation
void RMOL::EMDetruncator::unconstrain (HistoricalBookingHolder & ioHistoricalBookingHolder) static
Unconstrain the censored booking data using the Expection-Maximisation algorithm.
Definition at line 20 of file EMDetruncator.cpp.
References RMOL::HistoricalBookingHolder::getDemandMean(), RMOL::HistoricalBookingHolder::getListOfToBeUnconstrainedFlags(), RMOL::HistoricalBookingHolder::getNbOfFlights(), RMOL::HistoricalBookingHolder::getNbOfUncensoredBookings(), RMOL::HistoricalBookingHolder::getNbOfUncensoredData(), RMOL::HistoricalBookingHolder::getStandardDeviation(), RMOL::HistoricalBookingHolder::getUncensoredStandardDeviation(), RMOL::HistoricalBookingHolder::getUnconstrainedDemand(), and RMOL::HistoricalBookingHolder::setUnconstrainedDemand().
Referenced by RMOL::Detruncator::unconstrain().
The documentation for this class was generated from the following files:
rmol/bom/EMDetruncator.hpp
rmol/bom/EMDetruncator.cpp