RMOL::MCOptimiser Class Reference
RMOL::MCOptimiser Class Reference
#include <rmol/bom/MCOptimiser.hpp>
Static Public Member Functions
static void optimalOptimisationByMCIntegration (stdair::LegCabin &)
static stdair::GeneratedDemandVector_T generateDemandVector (const stdair::MeanValue_T &, const stdair::StdDevValue_T &, const stdair::NbOfSamples_T &)
static void optimisationByMCIntegration (stdair::LegCabin &)
Detailed Description
Utility methods for the Monte-Carlo algorithms.
Definition at line 19 of file MCOptimiser.hpp.
Member Function Documentation
void RMOL::MCOptimiser::optimalOptimisationByMCIntegration (stdair::LegCabin & ioLegCabin) static
Calculate the optimal protections for the set of buckets/classes given in input, and update those buckets accordingly.
The Monte Carlo Integration algorithm (see The Theory and Practice of Revenue Management, by Kalyan T. Talluri and Garret J. van Ryzin, Kluwer Academic Publishers, for the details) is used.
Definition at line 28 of file MCOptimiser.cpp.
Referenced by RMOL::Optimiser::optimalOptimisationByMCIntegration().
stdair::GeneratedDemandVector_T RMOL::MCOptimiser::generateDemandVector (const stdair::MeanValue_T & iMean, const stdair::StdDevValue_T & iStdDev, const stdair::NbOfSamples_T & K) static
Monte-Carlo
Definition at line 154 of file MCOptimiser.cpp.
Referenced by optimisationByMCIntegration().
void RMOL::MCOptimiser::optimisationByMCIntegration (stdair::LegCabin & ioLegCabin) static
Definition at line 175 of file MCOptimiser.cpp.
References RMOL::DEFAULT_NUMBER_OF_DRAWS_FOR_MC_SIMULATION, and generateDemandVector().
Referenced by RMOL::Optimiser::optimiseUsingOnDForecast().
The documentation for this class was generated from the following files:
rmol/bom/MCOptimiser.hpp
rmol/bom/MCOptimiser.cpp