RMOL::EmsrUtils Class Reference
RMOL::EmsrUtils Class Reference
#include <rmol/bom/EmsrUtils.hpp>
Static Public Member Functions
static void computeAggregatedVirtualClass (stdair::VirtualClassStruct &, stdair::VirtualClassStruct &)
static const stdair::ProtectionLevel_T computeProtectionLevel (stdair::VirtualClassStruct &, stdair::VirtualClassStruct &)
static const double computeEmsrValue (double, stdair::VirtualClassStruct &)
Detailed Description
Forward declarations.
Definition at line 19 of file EmsrUtils.hpp.
Member Function Documentation
void RMOL::EmsrUtils::computeAggregatedVirtualClass (stdair::VirtualClassStruct & ioAggregatedVirtualClass, stdair::VirtualClassStruct & ioCurrentVirtualClass) static
Compute the aggregated class/bucket of classes/buckets 1,..,j for EMSR-b algorithm.
Definition at line 19 of file EmsrUtils.cpp.
Referenced by RMOL::Emsr::heuristicOptimisationByEmsrB().
const stdair::ProtectionLevel_T RMOL::EmsrUtils::computeProtectionLevel (stdair::VirtualClassStruct & ioAggregatedVirtualClass, stdair::VirtualClassStruct & ioNextVirtualClass) static
Compute the protection level using the Little-Wood formular.
Definition at line 53 of file EmsrUtils.cpp.
Referenced by RMOL::Emsr::heuristicOptimisationByEmsrA(), and RMOL::Emsr::heuristicOptimisationByEmsrB().
const double RMOL::EmsrUtils::computeEmsrValue (double iCapacity, stdair::VirtualClassStruct & ioVirtualClass) static
Compute the EMSR value of a class/bucket.
Definition at line 80 of file EmsrUtils.cpp.
Referenced by RMOL::Emsr::heuristicOptimisationByEmsr().
The documentation for this class was generated from the following files:
rmol/bom/EmsrUtils.hpp
rmol/bom/EmsrUtils.cpp