RMOL::HistoricalBookingHolder Struct Reference
RMOL::HistoricalBookingHolder Struct Reference
#include <rmol/bom/HistoricalBookingHolder.hpp>
Public Member Functions
const short getNbOfFlights () const
const short getNbOfUncensoredData () const
const stdair::NbOfBookings_T getNbOfUncensoredBookings () const
const double getUncensoredStandardDeviation (const double &iMeanOfUncensoredBookings, const short iNbOfUncensoredData) const
const double getDemandMean () const
const double getStandardDeviation (const double) const
const std::vector< bool > getListOfToBeUnconstrainedFlags () const
const stdair::NbOfBookings_T & getHistoricalBooking (const short i) const
const stdair::NbOfBookings_T & getUnconstrainedDemand (const short i) const
const stdair::Flag_T & getCensorshipFlag (const short i) const
const stdair::NbOfBookings_T & getUnconstrainedDemandOnFirstElement () const
const stdair::NbOfBookings_T calculateExpectedDemand (const double, const double, const short, const stdair::NbOfBookings_T) const
void setUnconstrainedDemand (const stdair::NbOfBookings_T &iExpectedDemand, const short i)
void addHistoricalBooking (const HistoricalBooking &iHistoricalBooking)
void toStream (std::ostream &ioOut) const
const std::string describe () const
void display () const
virtual ~HistoricalBookingHolder ()
HistoricalBookingHolder ()
Detailed Description
Holder of a HistoricalBookingList object (for memory allocation and recollection purposes).
Definition at line 23 of file HistoricalBookingHolder.hpp.
Constructor & Destructor Documentation
RMOL::HistoricalBookingHolder::~HistoricalBookingHolder () virtual
Destructor.
Definition at line 23 of file HistoricalBookingHolder.cpp.
RMOL::HistoricalBookingHolder::HistoricalBookingHolder ()
Constructor.
Protected to force the use of the Factory.
Definition at line 19 of file HistoricalBookingHolder.cpp.
Member Function Documentation
const short RMOL::HistoricalBookingHolder::getNbOfFlights () const
Get number of flights.
Definition at line 28 of file HistoricalBookingHolder.cpp.
Referenced by RMOL::QForecasting::forecast(), RMOL::HybridForecasting::forecast(), RMOL::OldQFF::forecast(), RMOL::BasedForecasting::forecast(), and RMOL::EMDetruncator::unconstrain().
const short RMOL::HistoricalBookingHolder::getNbOfUncensoredData () const
Get number of uncensored booking data.
Definition at line 33 of file HistoricalBookingHolder.cpp.
Referenced by RMOL::EMDetruncator::unconstrain().
const stdair::NbOfBookings_T RMOL::HistoricalBookingHolder::getNbOfUncensoredBookings () const
Get number of uncensored bookings.
Definition at line 49 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getFlag(), and RMOL::HistoricalBooking::getNbOfBookings().
Referenced by RMOL::EMDetruncator::unconstrain().
const double RMOL::HistoricalBookingHolder::getUncensoredStandardDeviation (const double & iMeanOfUncensoredBookings, const short iNbOfUncensoredData) const
Get standard deviation of uncensored bookings.
Definition at line 69 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getNbOfBookings().
Referenced by RMOL::EMDetruncator::unconstrain().
const double RMOL::HistoricalBookingHolder::getDemandMean () const
Get mean of historical demand.
Definition at line 95 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getUnconstrainedDemand().
Referenced by RMOL::EMDetruncator::unconstrain().
const double RMOL::HistoricalBookingHolder::getStandardDeviation (const double iDemandMean) const
Get standard deviation of demand.
Definition at line 116 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getUnconstrainedDemand().
Referenced by RMOL::EMDetruncator::unconstrain().
const std::vector< bool > RMOL::HistoricalBookingHolder::getListOfToBeUnconstrainedFlags () const
Get the list of flags of need to be unconstrained.
Definition at line 140 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getFlag().
Referenced by RMOL::EMDetruncator::unconstrain().
const stdair::NbOfBookings_T & RMOL::HistoricalBookingHolder::getHistoricalBooking (const short i) const
Get the historical booking of the (i+1)-th flight.
Definition at line 161 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getNbOfBookings().
const stdair::NbOfBookings_T & RMOL::HistoricalBookingHolder::getUnconstrainedDemand (const short i) const
Get the unconstraining demand of the (i+1)-th flight.
Definition at line 169 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getUnconstrainedDemand().
Referenced by RMOL::QForecasting::forecast(), RMOL::HybridForecasting::forecast(), RMOL::OldQFF::forecast(), RMOL::BasedForecasting::forecast(), getUnconstrainedDemandOnFirstElement(), and RMOL::EMDetruncator::unconstrain().
const stdair::Flag_T & RMOL::HistoricalBookingHolder::getCensorshipFlag (const short i) const
Get the flag of the (i+1)-th flight.
Definition at line 177 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getFlag().
const stdair::NbOfBookings_T& RMOL::HistoricalBookingHolder::getUnconstrainedDemandOnFirstElement () const inline
Get the unconstraining demand of the first flight.
Definition at line 60 of file HistoricalBookingHolder.hpp.
References getUnconstrainedDemand().
const stdair::NbOfBookings_T RMOL::HistoricalBookingHolder::calculateExpectedDemand (const double iMean, const double iSD, const short i, const stdair::NbOfBookings_T iDemand) const
Calculate the expected demand.
Definition at line 191 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getNbOfBookings().
void RMOL::HistoricalBookingHolder::setUnconstrainedDemand (const stdair::NbOfBookings_T & iExpectedDemand, const short i)
Set the expected historical demand of the (i+1)-th flight.
Definition at line 185 of file HistoricalBookingHolder.cpp.
Referenced by RMOL::EMDetruncator::unconstrain().
void RMOL::HistoricalBookingHolder::addHistoricalBooking (const HistoricalBooking & iHistoricalBooking)
Add a HistoricalBooking object to the holder.
Definition at line 236 of file HistoricalBookingHolder.cpp.
Referenced by RMOL::BasedForecasting::prepareHistoricalBooking(), RMOL::QForecasting::preparePriceOrientedHistoricalBooking(), and RMOL::HybridForecasting::prepareProductOrientedHistoricalBooking().
void RMOL::HistoricalBookingHolder::toStream (std::ostream & ioOut) const
Dump a Business Object into an output stream.
Parameters
ostream& the output stream
Returns
ostream& the output stream.
Definition at line 241 of file HistoricalBookingHolder.cpp.
References RMOL::HistoricalBooking::getFlag(), RMOL::HistoricalBooking::getNbOfBookings(), and RMOL::HistoricalBooking::getUnconstrainedDemand().
Referenced by display().
const std::string RMOL::HistoricalBookingHolder::describe () const
Give a description of the structure (for display purposes).
Definition at line 265 of file HistoricalBookingHolder.cpp.
void RMOL::HistoricalBookingHolder::display () const
Display on standard output.
Definition at line 273 of file HistoricalBookingHolder.cpp.
References toStream().
The documentation for this struct was generated from the following files:
rmol/bom/HistoricalBookingHolder.hpp
rmol/bom/HistoricalBookingHolder.cpp