RMOL::HybridForecasting Class Reference
RMOL::HybridForecasting Class Reference
#include <rmol/command/HybridForecasting.hpp>
Static Public Member Functions
static bool forecast (stdair::SegmentCabin &, const stdair::Date_T &, const stdair::DTD_T &, const stdair::UnconstrainingMethod &, const stdair::NbOfSegments_T &)
static void prepareProductOrientedHistoricalBooking (const stdair::SegmentCabin &, const stdair::BookingClass &, const stdair::SegmentSnapshotTable &, HistoricalBookingHolder &, const stdair::DCP_T &, const stdair::DCP_T &, const stdair::NbOfSegments_T &, const stdair::NbOfSegments_T &)
Detailed Description
Class wrapping the forecasting algorithms.
Definition at line 21 of file HybridForecasting.hpp.
Member Function Documentation
bool RMOL::HybridForecasting::forecast (stdair::SegmentCabin & ioSegmentCabin, const stdair::Date_T & iCurrentDate, const stdair::DTD_T & iCurrentDTD, const stdair::UnconstrainingMethod & iUnconstrainingMethod, const stdair::NbOfSegments_T & iNbOfDepartedSegments) static
Forecast demand for a segment cabin.
Parameters
stdair::SegmentCabin& Current Segment Cabin
const stdair::Date_T& Current Date
const stdair::DTD_T& Current DTD
const stdair::UnconstrainingMethod& Method used for the unconstraining
const stdair::NbOfSegments_T& Number of usable historical segments
Definition at line 32 of file HybridForecasting.cpp.
References RMOL::Utilities::computeDistributionParameters(), RMOL::QForecasting::forecast(), RMOL::HistoricalBookingHolder::getNbOfFlights(), RMOL::SegmentSnapshotTableHelper::getNbOfSegmentAlreadyPassedThisDTD(), RMOL::HistoricalBookingHolder::getUnconstrainedDemand(), prepareProductOrientedHistoricalBooking(), and RMOL::Detruncator::unconstrain().
void RMOL::HybridForecasting::prepareProductOrientedHistoricalBooking (const stdair::SegmentCabin & iSegmentCabin, const stdair::BookingClass & iBookingClass, const stdair::SegmentSnapshotTable & iSegmentSnapshotTable, HistoricalBookingHolder & ioHBHolder, const stdair::DCP_T & iDCPBegin, const stdair::DCP_T & iDCPEnd, const stdair::NbOfSegments_T & iSegmentBegin, const stdair::NbOfSegments_T & iSegmentEnd) static
Prepare the historical product-oriented booking figures for a given cabin
Parameters
const stdair::DCP_T& DCP range start
const stdair::DCP_T& DCP range end
const stdair::NbOfSegments_T& Segment range start index
const stdair::NbOfSegments_T& Segment range end index
Definition at line 125 of file HybridForecasting.cpp.
References RMOL::HistoricalBookingHolder::addHistoricalBooking().
Referenced by forecast().
The documentation for this class was generated from the following files:
rmol/command/HybridForecasting.hpp
rmol/command/HybridForecasting.cpp