RMOL::Utilities Class Reference
RMOL::Utilities Class Reference
#include <rmol/bom/Utilities.hpp>
Static Public Member Functions
static void computeDistributionParameters (const stdair::UncDemVector_T &, stdair::MeanValue_T &, stdair::StdDevValue_T &)
static stdair::DCPList_T buildRemainingDCPList (const stdair::DTD_T &)
static stdair::DCPList_T buildPastDCPList (const stdair::DTD_T &)
static stdair::NbOfSegments_T getNbOfDepartedSimilarSegments (const stdair::SegmentCabin &, const stdair::Date_T &)
static stdair::BookingClassSellUpCurveMap_T computeSellUpFactorCurves (const stdair::FRAT5Curve_T &, const stdair::BookingClassList_T &)
static stdair::BookingClassDispatchingCurveMap_T computeDispatchingFactorCurves (const stdair::FRAT5Curve_T &, const stdair::BookingClassList_T &)
static void dispatchDemandForecast (const stdair::BookingClassDispatchingCurveMap_T &, const stdair::MeanValue_T &, const stdair::StdDevValue_T &, const stdair::DTD_T &)
static void dispatchDemandForecastForFA (const stdair::BookingClassSellUpCurveMap_T &, const stdair::MeanValue_T &, const stdair::StdDevValue_T &, const stdair::DTD_T &)
Detailed Description
Class holding helper methods.
Definition at line 20 of file Utilities.hpp.
Member Function Documentation
void RMOL::Utilities::computeDistributionParameters (const stdair::UncDemVector_T & iVector, stdair::MeanValue_T & ioMean, stdair::StdDevValue_T & ioStdDev) static
Compute the mean and the standard deviation from a set of samples.
Definition at line 27 of file Utilities.cpp.
Referenced by RMOL::QForecasting::forecast(), RMOL::HybridForecasting::forecast(), RMOL::OldQFF::forecast(), and RMOL::BasedForecasting::forecast().
stdair::DCPList_T RMOL::Utilities::buildRemainingDCPList (const stdair::DTD_T & iDTD) static
Build the list of remaining DCP's for the segment-date.
Definition at line 59 of file Utilities.cpp.
stdair::DCPList_T RMOL::Utilities::buildPastDCPList (const stdair::DTD_T & iDTD) static
Build the list of past DCP's for the segment-date.
Definition at line 84 of file Utilities.cpp.
stdair::NbOfSegments_T RMOL::Utilities::getNbOfDepartedSimilarSegments (const stdair::SegmentCabin & iSegmentCabin, const stdair::Date_T & iEventDate) static
Retrieve the number of departed similar segments.
Definition at line 104 of file Utilities.cpp.
References RMOL::SegmentSnapshotTableHelper::getNbOfSegmentAlreadyPassedThisDTD().
stdair::BookingClassSellUpCurveMap_T RMOL::Utilities::computeSellUpFactorCurves (const stdair::FRAT5Curve_T & iFRAT5Curve, const stdair::BookingClassList_T & iBCList) static
Precompute the sell-up factors for each class and each DCP.
Definition at line 116 of file Utilities.cpp.
Referenced by RMOL::QForecasting::forecast(), and RMOL::OldQFF::forecast().
stdair::BookingClassDispatchingCurveMap_T RMOL::Utilities::computeDispatchingFactorCurves (const stdair::FRAT5Curve_T & iFRAT5Curve, const stdair::BookingClassList_T & iBCList) static
Precompute the dispatching factors for each class and each DCP.
Definition at line 177 of file Utilities.cpp.
Referenced by RMOL::QForecasting::forecast().
void RMOL::Utilities::dispatchDemandForecast (const stdair::BookingClassDispatchingCurveMap_T & iBCDispatchingCurveMap, const stdair::MeanValue_T & iMean, const stdair::StdDevValue_T & iStdDev, const stdair::DTD_T & iCurrentDCP) static
Dispatching the demand forecast to all classes.
Definition at line 253 of file Utilities.cpp.
Referenced by RMOL::QForecasting::forecast().
void RMOL::Utilities::dispatchDemandForecastForFA (const stdair::BookingClassSellUpCurveMap_T & iBCSellUpCurveMap, const stdair::MeanValue_T & iMean, const stdair::StdDevValue_T & iStdDev, const stdair::DTD_T & iCurrentDCP) static
Dispatching the demand forecast to all classes for FA.
Definition at line 286 of file Utilities.cpp.
Referenced by RMOL::QForecasting::forecast().
The documentation for this class was generated from the following files:
rmol/bom/Utilities.hpp
rmol/bom/Utilities.cpp